version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
      - ./env.properties:/env.properties
  mysqldb:
    image: "mysql:8.2"
    restart: always
    ports:
      - 3606:3606
    networks:
      - springapimysql-net
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: movies
      MYSQL_USER: movies_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD: /run/secrets/db_password_root
    secrets:
      - db_root_password
      - db_password

networks:
  springapimysql-net:

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt